module.exports = {
  'main': 'SY',
  'tenants': [
    {
      code: 'SYFYB',
      name: '扶余北'
    }, {
      code: 'SYDHX',
      name: '德惠西'
    }, {
      code: 'SYCCZ',
      name: '长春'
    }, {
      code: 'SYCCX',
      name: '长春西'
    }, {
      code: 'SYGZL',
      name: '公主岭南'
    }, {
      code: 'SYSPD',
      name: '四平东'
    }, {
      code: 'SYCTX',
      name: '昌图西'
    }, {
      code: 'SYKYX',
      name: '开原西'
    }, {
      code: 'SYTLX',
      name: '铁岭西'
    }, {
      code: 'SYSYB',
      name: '沈阳北'
    }, {
      code: 'SYSYZ',
      name: '沈阳'
    }, {
      code: 'SYLYZ',
      name: '辽阳'
    }, {
      code: 'SYASX',
      name: '鞍山西'
    }, {
      code: 'SYHCX',
      name: '海城西'
    }, {
      code: 'SYYKD',
      name: '营口东'
    }, {
      code: 'SYGZX',
      name: '盖州西'
    }, {
      code: 'SYBYQ',
      name: '鲅鱼圈'
    }, {
      code: 'SYWFD',
      name: '瓦房店西'
    }, {
      code: 'SYPLD',
      name: '普湾'
    }, {
      code: 'SYDLB',
      name: '大连北'
    }, {
      code: 'SYDLZ',
      name: '大连'
    }
  ]
}
